#!/bin/sh

NAME=mindlink
PORT=8080
CONTAINER_PORT=8080
CONTAINER_RUNTIME=docker
DATA_PATH=data

cp -r frontend/ backend/static/

NAME=$NAME PORT=$PORT CONTAINER_PORT=$CONTAINER_PORT CONTAINER_RUNTIME=$CONTAINER_RUNTIME DATA_PATH=$DATA_PATH make -C backend image-run